In [1]:
import pandas as pd
import numpy as np
from scipy.stats import f
from markdownify import markdownify

In [2]:
f.ppf(1-.05, 2, 12)

3.8852938346523933

In [3]:
df = pd.DataFrame(np.zeros(1500).reshape(100,15), 
                  columns=['dfBtwn{}'.format(i) 
                           for i in range(1,16)],
                  index=['dfWthn{}'.format(i) 
                         for i in range(1,101)])

In [4]:
df.head()

,dfBtwn1,dfBtwn2,dfBtwn3,dfBtwn4,dfBtwn5,dfBtwn6,dfBtwn7,dfBtwn8,dfBtwn9,dfBtwn10,dfBtwn11,dfBtwn12,dfBtwn13,dfBtwn14,dfBtwn15
dfWthn1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dfWthn2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dfWthn3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dfWthn4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dfWthn5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
for b in range(0,15):
    for w in range(0,100):
        df.iloc[w,b] = f.ppf(1-.05, b+1, w+1)

In [6]:
df.head(n=15)

,dfBtwn1,dfBtwn2,dfBtwn3,dfBtwn4,dfBtwn5,dfBtwn6,dfBtwn7,dfBtwn8,dfBtwn9,dfBtwn10,dfBtwn11,dfBtwn12,dfBtwn13,dfBtwn14,dfBtwn15
dfWthn1,161.447639,199.500000,215.707345,224.583241,230.161878,233.986000,236.768400,238.882695,240.543255,241.881747,242.983458,243.906038,244.689847,245.363977,245.949926
dfWthn2,18.512821,19.000000,19.164292,19.246794,19.296410,19.329534,19.353218,19.370993,19.384826,19.395897,19.404958,19.412511,19.418904,19.424384,19.429135
dfWthn3,10.127964,9.552094,9.276628,9.117182,9.013455,8.940645,8.886743,8.845238,8.812300,8.785525,8.763333,8.744641,8.728681,8.714896,8.702870
dfWthn4,7.708647,6.944272,6.591382,6.388233,6.256057,6.163132,6.094211,6.041044,5.998779,5.964371,5.935813,5.911729,5.891144,5.873346,5.857805
dfWthn5,6.607891,5.786135,5.409451,5.192168,5.050329,4.950288,4.875872,4.818320,4.772466,4.735063,4.703967,4.677704,4.655225,4.635768,4.618759
dfWthn6,5.987378,5.143253,4.757063,4.533677,4.387374,4.283866,4.206658,4.146804,4.099016,4.059963,4.027442,3.999935,3.976363,3.955934,3.938058
dfWthn7,5.591448,4.737414,4.346831,4.120312,3.971523,3.865969,3.787044,3.725725,3.676675,3.636523,3.603037,3.574676,3.550343,3.529231,3.510740
dfWthn8,5.317655,4.458970,4.066181,3.837853,3.687499,3.580580,3.500464,3.438101,3.388130,3.347163,3.312951,3.283939,3.259019,3.237378,3.218406
dfWthn9,5.117355,4.256495,3.862548,3.633089,3.481659,3.373754,3.292746,3.229583,3.178893,3.137280,3.102485,3.072947,3.047549,3.025473,3.006102
dfWthn10,4.964603,4.102821,3.708265,3.478050,3.325835,3.217175,3.135465,3.071658,3.020383,2.978237,2.942957,2.912977,2.887175,2.864728,2.845017
dfWthn11,4.844336,3.982298,3.587434,3.356690,3.203874,3.094613,3.012330,2.947990,2.896223,2.853625,2.817930,2.787569,2.761417,2.738648,2.718640
dfWthn12,4.747225,3.885294,3.490295,3.259167,3.105875,2.996120,2.913358,2.848565,2.796375,2.753387,2.717331,2.686637,2.660177,2.637124,2.616851
dfWthn13,4.667193,3.805565,3.410534,3.179117,3.025438,2.915269,2.832098,2.766913,2.714356,2.671024,2.634650,2.603661,2.576927,2.553619,2.533110
dfWthn14,4.600110,3.738892,3.343889,3.112250,2.958249,2.847726,2.764199,2.698672,2.645791,2.602155,2.565497,2.534243,2.507263,2.483726,2.463003
dfWthn15,4.543077,3.682320,3.287382,3.055568,2.901295,2.790465,2.706627,2.640797,2.587626,2.543719,2.506806,2.475313,2.448110,2.424364,2.403447

In [7]:
df.to_html('Generated_F_Table.html')

In [8]:
file = open('Generated_F_Table.html', 'r').read()
html = markdownify(file)

mkdn = open('Generated_F_Table.md', 'w')
mkdn.writelines('# Generated_F_Table.md')
mkdn.writelines(html)
mkdn.close()